TRAINING_DATA = [
    # Weather intents
    ("What's the weather like?", {"intent": "get_weather"}),
    ("Tell me the weather in Berlin", {"intent": "get_weather"}),
    ("What is the weather in New York?", {"intent": "get_weather"}),
    ("How's the weather today?", {"intent": "get_weather"}),
    ("Will it rain tomorrow?", {"intent": "get_weather"}),
    ("Show me the weather forecast for London.", {"intent": "get_weather"}),
    ("Get the weather for Paris.", {"intent": "get_weather"}),
    ("What's the temperature right now?", {"intent": "get_weather"}),
    ("Is it sunny outside?", {"intent": "get_weather"}),
    ("Give me a weather update for Tokyo.", {"intent": "get_weather"}),
    ("What will the weather be like this weekend?", {"intent": "get_weather"}),
    ("Tell me if it will snow today.", {"intent": "get_weather"}),
    ("How hot will it be in Los Angeles?", {"intent": "get_weather"}),
    ("What was the weather like yesterday?", {"intent": "get_weather"}),
    ("What's the humidity level today?", {"intent": "get_weather"}),
    ("Is it cold in Chicago right now?", {"intent": "get_weather"}),
    ("Tell me the weather in my city.", {"intent": "get_weather"}),
    ("How's the weather looking for the week?", {"intent": "get_weather"}),
    ("What does the weather app say?", {"intent": "get_weather"}),
    ("Is it windy outside?", {"intent": "get_weather"}),

    # Website intents
    ("Open Google", {"intent": "open_website"}),
    ("Go to the website for New York travel", {"intent": "open_website"}),
    ("Launch Facebook", {"intent": "open_website"}),
    ("Open Wikipedia", {"intent": "open_website"}),
    ("Visit the official site for the weather", {"intent": "open_website"}),
    ("Show me the news website", {"intent": "open_website"}),
    ("Can you access Twitter?", {"intent": "open_website"}),
    ("Take me to Amazon", {"intent": "open_website"}),
    ("Open my email", {"intent": "open_website"}),
    ("Go to YouTube", {"intent": "open_website"}),
    ("Show me the shopping website", {"intent": "open_website"}),
    ("Launch LinkedIn", {"intent": "open_website"}),
    ("Access my favorite blog", {"intent": "open_website"}),
    ("Go to the cooking website", {"intent": "open_website"}),
    ("Can you open my social media?", {"intent": "open_website"}),
    ("Take me to the online store", {"intent": "open_website"}),
    ("Visit the official site for my favorite movie", {"intent": "open_website"}),
    ("Show me the sports website", {"intent": "open_website"}),
    ("Go to the education website", {"intent": "open_website"}),
    ("Open the finance website", {"intent": "open_website"}),

    # Time intents
    ("What time is it?", {"intent": "get_time"}),
    ("Tell me the current time", {"intent": "get_time"}),
    ("How late is it?", {"intent": "get_time"}),
    ("What is the hour?", {"intent": "get_time"}),
    ("Can you tell me the time now?", {"intent": "get_time"}),
    ("What's the current time right now?", {"intent": "get_time"}),
    ("What time do you have?", {"intent": "get_time"}),
    ("Is it time for dinner?", {"intent": "get_time"}),
    ("Tell me the time in 24-hour format", {"intent": "get_time"}),
    ("What time should I set my alarm?", {"intent": "get_time"}),
    ("Can you remind me what time it is?", {"intent": "get_time"}),
    ("What time is the meeting?", {"intent": "get_time"}),
    ("Tell me how many hours are left until midnight", {"intent": "get_time"}),
    ("Can you tell me when the sun sets?", {"intent": "get_time"}),
    ("What time do I need to leave?", {"intent": "get_time"}),
    ("How much time is left in the day?", {"intent": "get_time"}),
    ("What time zone are we in?", {"intent": "get_time"}),
    ("What time do you think it is in Tokyo?", {"intent": "get_time"}),
    ("Tell me the time difference between cities", {"intent": "get_time"}),
    ("What's the best time to call someone?", {"intent": "get_time"}),

    # Date intents
    ("Can you tell me the date?", {"intent": "get_date"}),
    ("What's today's date?", {"intent": "get_date"}),
    ("What is the current date?", {"intent": "get_date"}),
    ("Give me the date today", {"intent": "get_date"}),
    ("What day is it?", {"intent": "get_date"}),
    ("What's the date for next Monday?", {"intent": "get_date"}),
    ("Tell me the date of my birthday", {"intent": "get_date"}),
    ("What's the date tomorrow?", {"intent": "get_date"}),
    ("Can you tell me the first day of next month?", {"intent": "get_date"}),
    ("What is the last date of this month?", {"intent": "get_date"}),
    ("Give me today's full date", {"intent": "get_date"}),
    ("What was the date yesterday?", {"intent": "get_date"}),
    ("Tell me the date a week from now", {"intent": "get_date"}),
    ("What day of the week is it?", {"intent": "get_date"}),
    ("What date did we last talk?", {"intent": "get_date"}),
    ("How many days are left in the year?", {"intent": "get_date"}),
    ("What's the date for New Year's Eve?", {"intent": "get_date"}),
    ("Can you tell me the date of the last holiday?", {"intent": "get_date"}),
    ("What date does summer start?", {"intent": "get_date"}),
    ("Tell me the date I need to renew my subscription", {"intent": "get_date"}),

    # News intents
    ("What's the news today?", {"intent": "get_news"}),
    ("Give me the latest headlines", {"intent": "get_news"}),
    ("Show me today's news", {"intent": "get_news"}),
    ("Any news updates?", {"intent": "get_news"}),
    ("Tell me what’s happening in the world", {"intent": "get_news"}),
    ("Give me the top stories", {"intent": "get_news"}),
    ("What are the latest news articles?", {"intent": "get_news"}),
    ("What's the breaking news right now?", {"intent": "get_news"}),
    ("Tell me about the news in technology", {"intent": "get_news"}),
    ("Show me the sports news", {"intent": "get_news"}),
    ("Can you give me a summary of the news?", {"intent": "get_news"}),
    ("What's new in the world today?", {"intent": "get_news"}),
    ("Tell me about local news", {"intent": "get_news"}),
    ("What's the news about politics?", {"intent": "get_news"}),
    ("Give me a roundup of today's news", {"intent": "get_news"}),
    ("What are the latest updates in health news?", {"intent": "get_news"}),
    ("Share the latest entertainment news", {"intent": "get_news"}),
    ("Tell me what's trending today", {"intent": "get_news"}),
    ("What's happening in the economy?", {"intent": "get_news"}),
    ("Can you give me news from last week?", {"intent": "get_news"}),

    # Joke intents
    ("Tell me a joke", {"intent": "tell_joke"}),
    ("Make me laugh", {"intent": "tell_joke"}),
    ("Do you know any jokes?", {"intent": "tell_joke"}),
    ("Can you tell me something funny?", {"intent": "tell_joke"}),
    ("Share a joke with me", {"intent": "tell_joke"}),
    ("I want to hear a funny story", {"intent": "tell_joke"}),
    ("Tell me a knock-knock joke", {"intent": "tell_joke"}),
    ("What's a good joke?", {"intent": "tell_joke"}),
    ("Can you make me chuckle?", {"intent": "tell_joke"}),
    ("Tell me a pun", {"intent": "tell_joke"}),
    ("Do you have any dad jokes?", {"intent": "tell_joke"}),
    ("Can you crack a joke?", {"intent": "tell_joke"}),
    ("Tell me a short joke", {"intent": "tell_joke"}),
    ("Do you know any corny jokes?", {"intent": "tell_joke"}),
    ("Make a joke about cats", {"intent": "tell_joke"}),
    ("Can you tell a joke about programming?", {"intent": "tell_joke"}),
    ("What's your favorite joke?", {"intent": "tell_joke"}),
    ("I need a joke to lighten the mood", {"intent": "tell_joke"}),
    ("Tell me a joke related to science", {"intent": "tell_joke"}),
    ("Can you share a joke about food?", {"intent": "tell_joke"}),

    # Greeting intents
    ("Hi", {"intent": "greet"}),
    ("Hello", {"intent": "greet"}),
    ("Hey there", {"intent": "greet"}),
    ("Good morning", {"intent": "greet"}),
    ("Good evening", {"intent": "greet"}),
    ("What's up?", {"intent": "greet"}),
    ("How are you?", {"intent": "greet"}),
    ("Nice to meet you", {"intent": "greet"}),
    ("Howdy!", {"intent": "greet"}),
    ("Greetings!", {"intent": "greet"}),
    ("Hey!", {"intent": "greet"}),
    ("Hi there!", {"intent": "greet"}),
    ("Hello, how can I help?", {"intent": "greet"}),
    ("Good to see you!", {"intent": "greet"}),
    ("How's it going?", {"intent": "greet"}),
    ("What's new?", {"intent": "greet"}),
    ("What's good?", {"intent": "greet"}),
    ("Pleased to meet you!", {"intent": "greet"}),
    ("Hi! What can I do for you?", {"intent": "greet"}),
    ("Hello! What do you need?", {"intent": "greet"}),

    # Farewell intents
    ("Goodbye", {"intent": "farewell"}),
    ("Bye", {"intent": "farewell"}),
    ("See you later", {"intent": "farewell"}),
    ("Take care", {"intent": "farewell"}),
    ("Have a nice day", {"intent": "farewell"}),
    ("See you soon!", {"intent": "farewell"}),
    ("Catch you later", {"intent": "farewell"}),
    ("Farewell!", {"intent": "farewell"}),
    ("Good night", {"intent": "farewell"}),
    ("Until next time", {"intent": "farewell"}),
    ("Adios!", {"intent": "farewell"}),
    ("Later!", {"intent": "farewell"}),
    ("Talk to you later", {"intent": "farewell"}),
    ("I’m off now", {"intent": "farewell"}),
    ("Bye for now", {"intent": "farewell"}),
    ("So long!", {"intent": "farewell"}),
    ("See you next time", {"intent": "farewell"}),
    ("Goodbye for now", {"intent": "farewell"}),
    ("Until we meet again", {"intent": "farewell"}),
    ("Have a great day!", {"intent": "farewell"}),

    # Feedback intents
    ("That was helpful", {"intent": "feedback_positive"}),
    ("I liked that", {"intent": "feedback_positive"}),
    ("Good job", {"intent": "feedback_positive"}),
    ("That was great", {"intent": "feedback_positive"}),
    ("I didn't like that", {"intent": "feedback_negative"}),
    ("That wasn't helpful", {"intent": "feedback_negative"}),
    ("Please improve", {"intent": "feedback_negative"}),
    ("That's not what I meant", {"intent": "feedback_negative"}),
    ("I appreciate the help", {"intent": "feedback_positive"}),
    ("That was exactly what I needed", {"intent": "feedback_positive"}),
    ("I didn't find that useful", {"intent": "feedback_negative"}),
    ("Please do better next time", {"intent": "feedback_negative"}),
    ("You were really helpful", {"intent": "feedback_positive"}),
    ("I found this very helpful", {"intent": "feedback_positive"}),
    ("That didn't solve my problem", {"intent": "feedback_negative"}),
    ("I'm satisfied with your answer", {"intent": "feedback_positive"}),
    ("That could be better", {"intent": "feedback_negative"}),
    ("You did well!", {"intent": "feedback_positive"}),
    ("This was a waste of time", {"intent": "feedback_negative"}),
    ("Keep up the good work!", {"intent": "feedback_positive"}),

    # Fact intents
    ("Tell me a fact", {"intent": "get_fact"}),
    ("Give me a random fact", {"intent": "get_fact"}),
    ("I want to know a fact", {"intent": "get_fact"}),
    ("Share an interesting fact with me", {"intent": "get_fact"}),
    ("Tell me something I don't know", {"intent": "get_fact"}),
    ("What's a fun fact?", {"intent": "get_fact"}),
    ("Give me a trivia fact", {"intent": "get_fact"}),
    ("I need an interesting fact", {"intent": "get_fact"}),
    ("Tell me a random piece of trivia", {"intent": "get_fact"}),
    ("What's a surprising fact?", {"intent": "get_fact"}),
    ("Share a cool fact", {"intent": "get_fact"}),
    ("Can you tell me a fact about space?", {"intent": "get_fact"}),
    ("What's an interesting historical fact?", {"intent": "get_fact"}),
    ("Tell me something about animals", {"intent": "get_fact"}),
    ("Give me a fact about technology", {"intent": "get_fact"}),
    ("What's a fact about the ocean?", {"intent": "get_fact"}),
    ("Tell me a fact about the human body", {"intent": "get_fact"}),
    ("I want to know a fun fact about food", {"intent": "get_fact"}),
    ("What's a fact about the Earth?", {"intent": "get_fact"}),
    ("Tell me a fact about languages", {"intent": "get_fact"}),

    # Reminder intents
    ("Set a reminder for 3 PM", {"intent": "set_reminder"}),
    ("Remind me to buy groceries at 5", {"intent": "set_reminder"}),
    ("I need a reminder to call mom at noon", {"intent": "set_reminder"}),
    ("Can you remind me about the meeting tomorrow?", {"intent": "set_reminder"}),
    ("Please remind me to water the plants", {"intent": "set_reminder"}),
    ("Remind me to pick up the laundry", {"intent": "set_reminder"}),
    ("Set a reminder to pay the bills next week", {"intent": "set_reminder"}),
    ("I want to be reminded to exercise every day", {"intent": "set_reminder"}),
    ("Set an alarm for 7 AM", {"intent": "set_reminder"}),
    ("Don't forget to take the dog for a walk", {"intent": "set_reminder"}),
    ("Please remind me to send that email", {"intent": "set_reminder"}),
    ("Can you remind me about my appointment?", {"intent": "set_reminder"}),
    ("Set a reminder for my birthday next month", {"intent": "set_reminder"}),
    ("Remind me to check the mail", {"intent": "set_reminder"}),
    ("Please remind me about the doctor's appointment at 10", {"intent": "set_reminder"}),
    ("I need a reminder to finish my project", {"intent": "set_reminder"}),
    ("Can you remind me to take my medicine?", {"intent": "set_reminder"}),
    ("Remind me to buy tickets for the concert", {"intent": "set_reminder"}),
    ("I want to be reminded to clean the house", {"intent": "set_reminder"}),
    ("Please remind me to submit my report", {"intent": "set_reminder"}),

    # Story intents
    ("Tell me a story", {"intent": "tell_story"}),
    ("I want to hear a story", {"intent": "tell_story"}),
    ("Share a short story", {"intent": "tell_story"}),
    ("Can you tell me a bedtime story?", {"intent": "tell_story"}),
    ("Tell me a tale", {"intent": "tell_story"}),
    ("I’d like to hear a funny story", {"intent": "tell_story"}),
    ("Tell me a story about animals", {"intent": "tell_story"}),
    ("Share a story from history", {"intent": "tell_story"}),
    ("Can you narrate a fairy tale?", {"intent": "tell_story"}),
    ("Tell me a story about friendship", {"intent": "tell_story"}),
    ("I want to hear a scary story", {"intent": "tell_story"}),
    ("Can you tell me a story about love?", {"intent": "tell_story"}),
    ("Share a story that inspires", {"intent": "tell_story"}),
    ("Tell me an adventure story", {"intent": "tell_story"}),
    ("Give me a story that teaches a lesson", {"intent": "tell_story"}),
    ("Can you share a legendary tale?", {"intent": "tell_story"}),
    ("Tell me a story from your travels", {"intent": "tell_story"}),
    ("I’d like to hear a story about overcoming challenges", {"intent": "tell_story"}),
    ("Can you tell me a story about heroes?", {"intent": "tell_story"}),
    ("Share a story that makes people laugh", {"intent": "tell_story"}),

    # Music intents
    ("Play music", {"intent": "play_music"}),
    ("Start playing some songs", {"intent": "play_music"}),
    ("Can you play some tunes?", {"intent": "play_music"}),
    ("I want to listen to music", {"intent": "play_music"}),
    ("Play my favorite playlist", {"intent": "play_music"}),
    ("Put on some relaxing music", {"intent": "play_music"}),
    ("Can you play upbeat songs?", {"intent": "play_music"}),
    ("Start the music, please", {"intent": "play_music"}),
    ("Play some classical music", {"intent": "play_music"}),
    ("I’d like to hear some jazz", {"intent": "play_music"}),
    ("Put on some rock music", {"intent": "play_music"}),
    ("Play the latest hits", {"intent": "play_music"}),
    ("Can you play some chill music?", {"intent": "play_music"}),
    ("Start the party playlist", {"intent": "play_music"}),
    ("Play some instrumental music", {"intent": "play_music"}),
    ("Can you put on some background music?", {"intent": "play_music"}),
    ("Play something popular", {"intent": "play_music"}),
    ("Can you play my favorite song?", {"intent": "play_music"}),
    ("Start playing some oldies", {"intent": "play_music"}),
    ("I want to hear some music for studying", {"intent": "play_music"}),

    # Repeat intents
    ("Can you repeat that?", {"intent": "repeat"}),
    ("I didn't catch that, say it again", {"intent": "repeat"}),
    ("Please repeat your last statement", {"intent": "repeat"}),
    ("What did you say?", {"intent": "repeat"}),
    ("Can you say that once more?", {"intent": "repeat"}),
    ("I missed that, can you repeat?", {"intent": "repeat"}),
    ("Please say that again", {"intent": "repeat"}),
    ("I didn't hear you, can you repeat it?", {"intent": "repeat"}),
    ("Can you go over that again?", {"intent": "repeat"}),
    ("Could you clarify what you said?", {"intent": "repeat"}),
    ("I'm sorry, could you repeat that?", {"intent": "repeat"}),
    ("Say it again, please", {"intent": "repeat"}),
    ("What was that again?", {"intent": "repeat"}),
    ("I want to hear that one more time", {"intent": "repeat"}),
    ("Can you restate that?", {"intent": "repeat"}),
    ("Can you summarize what you just said?", {"intent": "repeat"}),
    ("Can you say that again, but slower?", {"intent": "repeat"}),
    ("I missed your last point, repeat it", {"intent": "repeat"}),
    ("I didn't get that, could you say it again?", {"intent": "repeat"}),
    ("What did you mean by that?", {"intent": "repeat"}),

    # Help intents
    ("What can you do?", {"intent": "help"}),
    ("Help me", {"intent": "help"}),
    ("Can you assist me?", {"intent": "help"}),
    ("What services do you provide?", {"intent": "help"}),
    ("Tell me about your capabilities", {"intent": "help"}),
    ("How can you help me?", {"intent": "help"}),
    ("What tasks can you perform?", {"intent": "help"}),
    ("Give me a list of commands", {"intent": "help"}),
    ("What are your features?", {"intent": "help"}),
    ("Can you provide some examples of what you can do?", {"intent": "help"}),
    ("I need help with something", {"intent": "help"}),
    ("Tell me how to use you", {"intent": "help"}),
    ("What should I ask you?", {"intent": "help"}),
    ("Can you guide me on how to interact with you?", {"intent": "help"}),
    ("What are your skills?", {"intent": "help"}),
    ("How do I get you to do something?", {"intent": "help"}),
    ("Can you help me find information?", {"intent": "help"}),
    ("Tell me about your main functions", {"intent": "help"}),
    ("How do I ask you questions?", {"intent": "help"}),
    ("What commands do you recognize?", {"intent": "help"}),

        # Increase Volume
    ("Turn up the volume", {"intent": "volume_up"}),
    ("Increase the volume", {"intent": "volume_up"}),
    ("Volume up", {"intent": "volume_up"}),
    ("Make it louder", {"intent": "volume_up"}),
    ("Can you raise the volume?", {"intent": "volume_up"}),
    ("Boost the volume", {"intent": "volume_up"}),
    ("I want it louder", {"intent": "volume_up"}),
    ("Turn the volume up", {"intent": "volume_up"}),
    ("Crank up the volume", {"intent": "volume_up"}),
    ("Louder, please", {"intent": "volume_up"}),
    ("Volume increase", {"intent": "volume_up"}),
    ("Raise the volume a bit", {"intent": "volume_up"}),
    ("Set the volume higher", {"intent": "volume_up"}),
    ("Make it a bit louder", {"intent": "volume_up"}),
    ("Could you increase the volume?", {"intent": "volume_up"}),
    ("Give me more volume", {"intent": "volume_up"}),
    ("I need more sound", {"intent": "volume_up"}),
    ("How about more volume?", {"intent": "volume_up"}),
    ("Put the volume up", {"intent": "volume_up"}),
    ("Can you amplify the sound?", {"intent": "volume_up"}),
    ("Adjust the volume to a higher level", {"intent": "volume_up"}),

    # Decrease Volume
    ("Turn down the volume", {"intent": "volume_down"}),
    ("Decrease the volume", {"intent": "volume_down"}),
    ("Volume down", {"intent": "volume_down"}),
    ("Make it quieter", {"intent": "volume_down"}),
    ("Can you lower the volume?", {"intent": "volume_down"}),
    ("Reduce the volume", {"intent": "volume_down"}),
    ("I want it softer", {"intent": "volume_down"}),
    ("Turn the volume down", {"intent": "volume_down"}),
    ("Lower the volume a bit", {"intent": "volume_down"}),
    ("Quieter, please", {"intent": "volume_down"}),
    ("Volume decrease", {"intent": "volume_down"}),
    ("Reduce the sound level", {"intent": "volume_down"}),
    ("Can you make it less loud?", {"intent": "volume_down"}),
    ("Bring the volume down", {"intent": "volume_down"}),
    ("Please turn down the sound", {"intent": "volume_down"}),
    ("I need less sound", {"intent": "volume_down"}),
    ("Can you lower the sound a bit?", {"intent": "volume_down"}),
    ("What about less volume?", {"intent": "volume_down"}),
    ("Can you mute it a little?", {"intent": "volume_down"}),
    ("Adjust the volume to a lower level", {"intent": "volume_down"}),

    # Set Specific Volume
    ("Set volume to 50%", {"intent": "set_volume"}),
    ("Adjust volume to 30%", {"intent": "set_volume"}),
    ("Make the volume 70%", {"intent": "set_volume"}),
    ("Put the volume at 20%", {"intent": "set_volume"}),
    ("I want the sound at 40%", {"intent": "set_volume"}),
    ("Can you set the volume to 80%?", {"intent": "set_volume"}),
    ("Volume should be 60%", {"intent": "set_volume"}),
    ("Set the volume level to 90%", {"intent": "set_volume"}),
    ("Change volume to 10%", {"intent": "set_volume"}),
    ("Make the sound level 100%", {"intent": "set_volume"}),
    ("Please set the volume to 15%", {"intent": "set_volume"}),
    ("Adjust sound to 25%", {"intent": "set_volume"}),
    ("Set the audio to 55%", {"intent": "set_volume"}),
    ("Can you put the volume at 75%?", {"intent": "set_volume"}),
    ("Volume should be 45%", {"intent": "set_volume"}),
    ("Change the volume to 35%", {"intent": "set_volume"}),
    ("Make the audio level 65%", {"intent": "set_volume"}),
    ("Set the sound to 95%", {"intent": "set_volume"}),
    ("I want the volume at 5%", {"intent": "set_volume"}),
    ("Please adjust the volume to 85%", {"intent": "set_volume"}),






    # Weather intents
    ("Πώς είναι ο καιρός;", {"intent": "get_weather"}),
    ("Πες μου τον καιρό στην Αθήνα.", {"intent": "get_weather"}),
    ("Ποια είναι η θερμοκρασία στο Λονδίνο;", {"intent": "get_weather"}),
    ("Θα βρέξει αύριο;", {"intent": "get_weather"}),
    ("Ποια είναι η πρόβλεψη για τη Θεσσαλονίκη;", {"intent": "get_weather"}),
    ("Δείξε μου τον καιρό για την Κρήτη.", {"intent": "get_weather"}),
    ("Τι καιρό κάνει σήμερα στην Πάτρα;", {"intent": "get_weather"}),
    ("Πώς είναι ο καιρός στο Μόναχο;", {"intent": "get_weather"}),
    ("Πες μου αν θα χιονίσει αύριο.", {"intent": "get_weather"}),
    ("Θέλω να μάθω τον καιρό στο Βερολίνο.", {"intent": "get_weather"}),
    ("Ποια είναι η υγρασία σήμερα;", {"intent": "get_weather"}),
    ("Είναι κρύο στην Θεσσαλονίκη;", {"intent": "get_weather"}),
    ("Ποια είναι η πρόβλεψη για το Σαββατοκύριακο;", {"intent": "get_weather"}),
    ("Δώσε μου τον καιρό για αύριο.", {"intent": "get_weather"}),
    ("Πώς θα είναι ο καιρός την επόμενη εβδομάδα;", {"intent": "get_weather"}),
    ("Είναι ζεστά σήμερα;", {"intent": "get_weather"}),
    ("Πες μου για τον καιρό στην Πάρο.", {"intent": "get_weather"}),
    ("Πώς είναι ο καιρός για διακοπές;", {"intent": "get_weather"}),
    ("Θέλω να ξέρω αν θα βρέξει το βράδυ.", {"intent": "get_weather"}),
    ("Δώσε μου μια ενημέρωση για τον καιρό.", {"intent": "get_weather"}),

    # Website intents
    ("Άνοιξε το Google.", {"intent": "open_website"}),
    ("Πήγαινε στην ιστοσελίδα του καιρού.", {"intent": "open_website"}),
    ("Ανοίξε το Facebook.", {"intent": "open_website"}),
    ("Πήγαινε στο Wikipedia.", {"intent": "open_website"}),
    ("Επισκέψου την επίσημη ιστοσελίδα για ταξίδια.", {"intent": "open_website"}),
    ("Δείξε μου τις ειδήσεις.", {"intent": "open_website"}),
    ("Άνοιξε το YouTube.", {"intent": "open_website"}),
    ("Πες μου την ιστοσελίδα για την εκπαίδευση.", {"intent": "open_website"}),
    ("Δείξε μου την ιστοσελίδα των ταινιών.", {"intent": "open_website"}),
    ("Πήγαινε στο Amazon.", {"intent": "open_website"}),
    ("Ανοίξε τον ιστότοπο της μουσικής.", {"intent": "open_website"}),
    ("Δείξε μου το Twitter.", {"intent": "open_website"}),
    ("Πήγαινε στο LinkedIn.", {"intent": "open_website"}),
    ("Άνοιξε το Instagram.", {"intent": "open_website"}),
    ("Πήγαινε στην ιστοσελίδα για συνταγές.", {"intent": "open_website"}),
    ("Ανοίξε την ιστοσελίδα για τις προσφορές.", {"intent": "open_website"}),
    ("Δείξε μου την ιστοσελίδα με τις κριτικές.", {"intent": "open_website"}),
    ("Πήγαινε στο επίσημο σάιτ της αγαπημένης μου ταινίας.", {"intent": "open_website"}),
    ("Άνοιξε το μπλογκ μου.", {"intent": "open_website"}),
    ("Ανοίξε την ιστοσελίδα της εταιρείας μου.", {"intent": "open_website"}),

    # Time intents
    ("Τι ώρα είναι;", {"intent": "get_time"}),
    ("Πες μου την τρέχουσα ώρα.", {"intent": "get_time"}),
    ("Πόσο είναι;", {"intent": "get_time"}),
    ("Ποιό είναι το ρολόι;", {"intent": "get_time"}),
    ("Κάνε μου γνωστό την ώρα.", {"intent": "get_time"}),
    ("Πες μου αν είναι αργά.", {"intent": "get_time"}),
    ("Ποιό είναι το ρολόι τώρα;", {"intent": "get_time"}),
    ("Πόσες ώρες είναι;", {"intent": "get_time"}),
    ("Πες μου την ώρα σε 24ωρη μορφή.", {"intent": "get_time"}),
    ("Πόση ώρα έμεινε μέχρι το μεσημέρι;", {"intent": "get_time"}),
    ("Ποιό είναι το πιο κατάλληλο για να καλέσω κάποιον;", {"intent": "get_time"}),
    ("Πες μου την ώρα που θα ξεκινήσει η συνάντηση.", {"intent": "get_time"}),
    ("Πόση ώρα έχει απομείνει στην ημέρα;", {"intent": "get_time"}),
    ("Πες μου πότε δύει ο ήλιος.", {"intent": "get_time"}),
    ("Ποιό είναι το ρολόι στην Κύπρο;", {"intent": "get_time"}),
    ("Πες μου πόσες ώρες έχει το Σαββατοκύριακο;", {"intent": "get_time"}),
    ("Πες μου πόσες ώρες είναι στην Αμερική;", {"intent": "get_time"}),
    ("Πες μου την ώρα που είχαμε τελευταία φορά.", {"intent": "get_time"}),
    ("Ποιό είναι το πιο κατάλληλο για να καλέσω;", {"intent": "get_time"}),
    ("Πες μου ποια ώρα είναι στη Γαλλία.", {"intent": "get_time"}),

    # Date intents
    ("Ποια είναι η ημερομηνία σήμερα;", {"intent": "get_date"}),
    ("Τι ημερομηνία έχουμε;", {"intent": "get_date"}),
    ("Πες μου την ημερομηνία του Σαββατοκύριακου.", {"intent": "get_date"}),
    ("Ποιό είναι το πρώτο ημερομηνία του μήνα;", {"intent": "get_date"}),
    ("Πες μου την ημερομηνία που πρέπει να ανανεώσω την συνδρομή μου.", {"intent": "get_date"}),
    ("Τι ημερομηνία έχουμε αύριο;", {"intent": "get_date"}),
    ("Πες μου πότε είναι η τελευταία γιορτή.", {"intent": "get_date"}),
    ("Ποιό είναι το ημερολόγιο σήμερα;", {"intent": "get_date"}),
    ("Πόσες ημέρες έχουν απομείνει μέχρι την Πρωτοχρονιά;", {"intent": "get_date"}),
    ("Ποιές είναι οι ημερομηνίες των διακοπών;", {"intent": "get_date"}),
    ("Πες μου την ημερομηνία της τελευταίας μας συνάντησης.", {"intent": "get_date"}),
    ("Ποιό είναι το ημερολόγιο για τον επόμενο μήνα;", {"intent": "get_date"}),
    ("Ποιό είναι το ημερολόγιο για τη διάρκεια του έτους;", {"intent": "get_date"}),
    ("Πες μου την ημέρα που θα έρθει η επόμενη γιορτή.", {"intent": "get_date"}),
    ("Πες μου την ημερομηνία που πρέπει να φύγω.", {"intent": "get_date"}),
    ("Ποιές είναι οι γιορτές του μήνα;", {"intent": "get_date"}),
    ("Ποιό είναι το ημερολόγιο για τις διακοπές;", {"intent": "get_date"}),
    ("Πες μου για τις ημερομηνίες που θα είναι οι γιορτές.", {"intent": "get_date"}),
    ("Πόσες ημέρες έχουν απομείνει μέχρι το τέλος του μήνα;", {"intent": "get_date"}),
    ("Πες μου πόσες ημέρες έχει η εβδομάδα;", {"intent": "get_date"}),

    # News intents
    ("Πες μου τις ειδήσεις σήμερα.", {"intent": "get_news"}),
    ("Τι νέο υπάρχει στον κόσμο;", {"intent": "get_news"}),
    ("Δώσε μου τα τελευταία νέα.", {"intent": "get_news"}),
    ("Ποιες είναι οι πιο σημαντικές ειδήσεις;", {"intent": "get_news"}),
    ("Πες μου για τις ειδήσεις από το πολιτικό τομέα.", {"intent": "get_news"}),
    ("Πες μου τις ειδήσεις για τον αθλητισμό.", {"intent": "get_news"}),
    ("Τι είναι οι τελευταίες ενημερώσεις;", {"intent": "get_news"}),
    ("Πες μου τα νέα από την Ελλάδα.", {"intent": "get_news"}),
    ("Δώσε μου πληροφορίες για τις διεθνείς ειδήσεις.", {"intent": "get_news"}),
    ("Πες μου τις ειδήσεις που αφορούν την υγεία.", {"intent": "get_news"}),
    ("Ποιες είναι οι τελευταίες ειδήσεις σχετικά με την οικονομία;", {"intent": "get_news"}),
    ("Πες μου για τις τελευταίες ειδήσεις στην τεχνολογία.", {"intent": "get_news"}),
    ("Ποιες είναι οι πιο ενδιαφέρουσες ειδήσεις;", {"intent": "get_news"}),
    ("Δώσε μου τις πιο σημαντικές ειδήσεις σήμερα.", {"intent": "get_news"}),
    ("Πες μου για τις ειδήσεις στην ψυχαγωγία.", {"intent": "get_news"}),
    ("Τι νέο υπάρχει στην πολιτική;", {"intent": "get_news"}),
    ("Πες μου για τις ειδήσεις της ημέρας.", {"intent": "get_news"}),
    ("Ποιες είναι οι πιο ενδιαφέρουσες ειδήσεις σήμερα;", {"intent": "get_news"}),
    ("Δώσε μου την τελευταία είδηση.", {"intent": "get_news"}),
    ("Πες μου για την κατάσταση στην κοινωνία;", {"intent": "get_news"}),

    # Joke intents
    ("Πες μου ένα ανέκδοτο.", {"intent": "tell_joke"}),
    ("Κάνε με να γελάσω.", {"intent": "tell_joke"}),
    ("Γνωρίζεις κάποιο ανέκδοτο;", {"intent": "tell_joke"}),
    ("Πες μου κάτι αστείο.", {"intent": "tell_joke"}),
    ("Πες μου ένα αστείο.", {"intent": "tell_joke"}),
    ("Κάνε με να γελάσω παρακαλώ.", {"intent": "tell_joke"}),
    ("Πες μου έναν περίεργο αστείο.", {"intent": "tell_joke"}),
    ("Κάνε μου μια πλάκα.", {"intent": "tell_joke"}),
    ("Πες μου ένα αστείο για ζώα.", {"intent": "tell_joke"}),
    ("Πες μου ένα ανέκδοτο από το σχολείο.", {"intent": "tell_joke"}),
    ("Δώσε μου ένα αστείο με καφέ.", {"intent": "tell_joke"}),
    ("Πες μου ένα κακό ανέκδοτο.", {"intent": "tell_joke"}),
    ("Δώσε μου ένα ανέκδοτο για γάτες.", {"intent": "tell_joke"}),
    ("Πες μου ένα αστείο που να σε γελάσει.", {"intent": "tell_joke"}),
    ("Πες μου ένα ανέκδοτο για σπασμένα τηλέφωνα.", {"intent": "tell_joke"}),
    ("Πες μου ένα ανέκδοτο για τον καθηγητή.", {"intent": "tell_joke"}),
    ("Κάνε μου ένα αστείο για το φαγητό.", {"intent": "tell_joke"}),
    ("Πες μου ένα ανέκδοτο που να είναι αστείο.", {"intent": "tell_joke"}),
    ("Δώσε μου ένα αστείο με μουσική.", {"intent": "tell_joke"}),
    ("Πες μου ένα αστείο για τις σχέσεις.", {"intent": "tell_joke"}),

    # Greeting intents
    ("Γεια σου!", {"intent": "greet"}),
    ("Καλημέρα!", {"intent": "greet"}),
    ("Καλησπέρα!", {"intent": "greet"}),
    ("Γειά!", {"intent": "greet"}),
    ("Πώς είσαι;", {"intent": "greet"}),
    ("Τι κάνεις;", {"intent": "greet"}),
    ("Ελπίζω να είσαι καλά.", {"intent": "greet"}),
    ("Χαίρομαι που σε βλέπω.", {"intent": "greet"}),
    ("Καληνύχτα!", {"intent": "greet"}),
    ("Γειά σου φίλε!", {"intent": "greet"}),
    ("Χαίρετε!", {"intent": "greet"}),
    ("Πώς πάει;", {"intent": "greet"}),
    ("Χαίρομαι που μιλάμε.", {"intent": "greet"}),
    ("Καλώς ήρθες!", {"intent": "greet"}),
    ("Πώς να σε βοηθήσω;", {"intent": "greet"}),
    ("Καλημέρα, πώς μπορώ να σε βοηθήσω;", {"intent": "greet"}),
    ("Καλησπέρα, τι να κάνω;", {"intent": "greet"}),
    ("Γεια σου, ποια είναι η ανάγκη σου;", {"intent": "greet"}),
    ("Καληνύχτα, πώς μπορώ να σε εξυπηρετήσω;", {"intent": "greet"}),

    # Farewell intents
    ("Αντίο!", {"intent": "farewell"}),
    ("Τα λέμε αργότερα.", {"intent": "farewell"}),
    ("Καλή συνέχεια!", {"intent": "farewell"}),
    ("Τα ξαναλέμε!", {"intent": "farewell"}),
    ("Ευχαριστώ, τα λέμε!", {"intent": "farewell"}),
    ("Να έχεις μια καλή μέρα!", {"intent": "farewell"}),
    ("Στο επανιδείν!", {"intent": "farewell"}),
    ("Καλή τύχη!", {"intent": "farewell"}),
    ("Τα λέμε σύντομα!", {"intent": "farewell"}),
    ("Αναμένοντας ξανά!", {"intent": "farewell"}),
    ("Σου εύχομαι τα καλύτερα!", {"intent": "farewell"}),
    ("Ευχαριστώ για τη βοήθεια!", {"intent": "farewell"}),
    ("Θα ξαναμιλήσουμε!", {"intent": "farewell"}),
    ("Πες μου ξανά!", {"intent": "farewell"}),
    ("Ελπίζω να ξανασυναντηθούμε!", {"intent": "farewell"}),
    ("Περάστε καλά!", {"intent": "farewell"}),
    ("Ελπίζω να τα πούμε σύντομα!", {"intent": "farewell"}),
    ("Ευχαριστώ για την παρέα!", {"intent": "farewell"}),
    ("Σου εύχομαι μια υπέροχη μέρα!", {"intent": "farewell"}),

    # Help intents
    ("Τι μπορείς να κάνεις;", {"intent": "help"}),
    ("Μπορείς να με βοηθήσεις;", {"intent": "help"}),
    ("Πες μου για τις δυνατότητές σου.", {"intent": "help"}),
    ("Πώς μπορώ να σε χρησιμοποιήσω;", {"intent": "help"}),
    ("Ποιες είναι οι δυνατότητές σου;", {"intent": "help"}),
    ("Πες μου για τις υπηρεσίες σου.", {"intent": "help"}),
    ("Πώς να κάνω μια ερώτηση;", {"intent": "help"}),
    ("Ποιες πληροφορίες μπορείς να μου δώσεις;", {"intent": "help"}),
    ("Πες μου αν μπορείς να με εξυπηρετήσεις.", {"intent": "help"}),
    ("Μπορείς να με ενημερώσεις;", {"intent": "help"}),
    ("Πες μου πώς να με ρωτήσω.", {"intent": "help"}),
    ("Είσαι έτοιμος να με βοηθήσεις;", {"intent": "help"}),
    ("Μπορείς να κάνεις αναζητήσεις;", {"intent": "help"}),
    ("Πες μου για το πώς λειτουργείς.", {"intent": "help"}),
    ("Μπορείς να μου πεις ποιοι είναι οι φίλοι σου;", {"intent": "help"}),
    ("Τι μπορείς να μου δώσεις;", {"intent": "help"}),
    ("Πες μου πώς να με ρωτήσω για μια δουλειά.", {"intent": "help"}),
    ("Μπορείς να κάνεις υπολογισμούς;", {"intent": "help"}),
    ("Μπορείς να βοηθήσεις σε ταξίδια;", {"intent": "help"}),
    ("Μπορείς να δώσεις συμβουλές;", {"intent": "help"}),

    # Feedback intents
    ("Αυτό ήταν χρήσιμο.", {"intent": "feedback_positive"}),
    ("Μου άρεσε αυτό.", {"intent": "feedback_positive"}),
    ("Καλή δουλειά.", {"intent": "feedback_positive"}),
    ("Αυτό ήταν υπέροχο.", {"intent": "feedback_positive"}),
    ("Δεν μου άρεσε αυτό.", {"intent": "feedback_negative"}),
    ("Αυτό δεν ήταν χρήσιμο.", {"intent": "feedback_negative"}),
    ("Παρακαλώ βελτίωσε.", {"intent": "feedback_negative"}),
    ("Δεν ήταν αυτό που εννοούσα.", {"intent": "feedback_negative"}),
    ("Ευχαριστώ για την βοήθεια.", {"intent": "feedback_positive"}),
    ("Ήταν καλή η βοήθεια.", {"intent": "feedback_positive"}),
    ("Σου δίνω θετική ανατροφοδότηση.", {"intent": "feedback_positive"}),
    ("Θα ήθελα καλύτερες απαντήσεις.", {"intent": "feedback_negative"}),
    ("Αυτή η απάντηση δεν με ικανοποιεί.", {"intent": "feedback_negative"}),
    ("Συμφωνώ με την απάντηση.", {"intent": "feedback_positive"}),
    ("Μου άρεσε η απάντηση.", {"intent": "feedback_positive"}),
    ("Θα ήθελα περισσότερες πληροφορίες.", {"intent": "feedback_negative"}),
    ("Αυτή η απάντηση ήταν ωραία.", {"intent": "feedback_positive"}),
    ("Αυτό δεν ήταν καλό.", {"intent": "feedback_negative"}),
    ("Συχνά τα ίδια λάθη.", {"intent": "feedback_negative"}),
    ("Η βοήθεια ήταν ακριβής.", {"intent": "feedback_positive"}),

        # Increase Volume
    ("Αύξησε την ένταση", {"intent": "volume_up"}),
    ("Κάνε την ένταση πιο δυνατή", {"intent": "volume_up"}),
    ("Ενίσχυσε την ένταση", {"intent": "volume_up"}),
    ("Πες πιο δυνατά", {"intent": "volume_up"}),
    ("Μπορείς να ανεβάσεις την ένταση;", {"intent": "volume_up"}),
    ("Κάνε την πιο δυνατή", {"intent": "volume_up"}),
    ("Θέλω περισσότερη ένταση", {"intent": "volume_up"}),
    ("Αύξησε την ένταση λίγο", {"intent": "volume_up"}),
    ("Αύξησε την ένταση παρακαλώ", {"intent": "volume_up"}),
    ("Κάνε την ένταση πιο υψηλή", {"intent": "volume_up"}),
    ("Δώσε μου περισσότερη ένταση", {"intent": "volume_up"}),
    ("Αύξησε την ένταση κατά 10%", {"intent": "volume_up"}),
    ("Κάνε την ένταση στο 100%", {"intent": "volume_up"}),
    ("Μπορείς να ενισχύσεις την ένταση;", {"intent": "volume_up"}),
    ("Ποια είναι η ένταση;", {"intent": "volume_up"}),
    ("Δώσε μου πιο δυνατή μουσική", {"intent": "volume_up"}),
    ("Κάνε την ένταση να χτυπήσει το ταβάνι", {"intent": "volume_up"}),
    ("Πόση είναι η ένταση;", {"intent": "volume_up"}),
    ("Αύξησε την ένταση στον ανώτερο βαθμό", {"intent": "volume_up"}),
    ("Πες το πιο δυνατά", {"intent": "volume_up"}),
    ("Άνοιξε την φωνή", {"intent": "volume_up"}),

    # Decrease Volume
    ("Μείωσε την ένταση", {"intent": "volume_down"}),
    ("Κάνε την ένταση πιο χαμηλή", {"intent": "volume_down"}),
    ("Μείωσε τον ήχο", {"intent": "volume_down"}),
    ("Κάνε το πιο ήσυχο", {"intent": "volume_down"}),
    ("Μπορείς να χαμηλώσεις την ένταση;", {"intent": "volume_down"}),
    ("Δίωξε την ένταση", {"intent": "volume_down"}),
    ("Θέλω λιγότερη ένταση", {"intent": "volume_down"}),
    ("Μείωσε την ένταση λίγο", {"intent": "volume_down"}),
    ("Πες το πιο ήσυχα", {"intent": "volume_down"}),
    ("Η ένταση είναι πολύ δυνατή", {"intent": "volume_down"}),
    ("Μείωσε την ένταση κατά 10%", {"intent": "volume_down"}),
    ("Αφήστε το πιο χαμηλά", {"intent": "volume_down"}),
    ("Μπορείς να το κάνεις λιγότερο δυνατό;", {"intent": "volume_down"}),
    ("Ποια είναι η τρέχουσα ένταση;", {"intent": "volume_down"}),
    ("Δώσε μου λιγότερη ένταση", {"intent": "volume_down"}),
    ("Κάνε το πιο ήσυχο παρακαλώ", {"intent": "volume_down"}),
    ("Μπορείς να το κάνεις πιο ήσυχο;", {"intent": "volume_down"}),
    ("Μπορείς να κάνεις την ένταση πιο χαμηλή;", {"intent": "volume_down"}),
    ("Πες το με λιγότερη ένταση", {"intent": "volume_down"}),
    ("Αφήστε το ήσυχο", {"intent": "volume_down"}),
    ("Χαμήλωσε την φωνή", {"intent": "volume_down"}),

    # Set Specific Volume
    ("Θέσε την ένταση στο 50%", {"intent": "set_volume"}),
    ("Ρύθμισε την ένταση στο 30%", {"intent": "set_volume"}),
    ("Κάνε την ένταση 70%", {"intent": "set_volume"}),
    ("Βάλε την ένταση στο 20%", {"intent": "set_volume"}),
    ("Θέλω τον ήχο στο 40%", {"intent": "set_volume"}),
    ("Μπορείς να ρυθμίσεις την ένταση στο 80%;", {"intent": "set_volume"}),
    ("Η ένταση θα πρέπει να είναι 60%", {"intent": "set_volume"}),
    ("Ρύθμισε την ένταση στο 90%", {"intent": "set_volume"}),
    ("Αλλάξε την ένταση στο 10%", {"intent": "set_volume"}),
    ("Κάνε την ένταση 100%", {"intent": "set_volume"}),
    ("Παρακαλώ θέσε την ένταση στο 15%", {"intent": "set_volume"}),
    ("Ρύθμισε τον ήχο στο 25%", {"intent": "set_volume"}),
    ("Ορίστε τον ήχο στο 55%", {"intent": "set_volume"}),
    ("Μπορείς να βάλεις την ένταση στο 75%;", {"intent": "set_volume"}),
    ("Η ένταση θα πρέπει να είναι 45%", {"intent": "set_volume"}),
    ("Αλλάξε την ένταση στο 35%", {"intent": "set_volume"}),
    ("Κάνε το επίπεδο ήχου 65%", {"intent": "set_volume"}),
    ("Θέσε τον ήχο στο 95%", {"intent": "set_volume"}),
    ("Θέλω την ένταση στο 5%", {"intent": "set_volume"}),
    ("Παρακαλώ ρύθμισε την ένταση στο 85%", {"intent": "set_volume"}),
    ("Φωνή 50%", {"intent": "set_volume"}),

]
